sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t swintonp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true swintonp/docker-react npm run test
